version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway/ApiGateway
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: "API Gateway"
    networks:
      - task-network

  service_users:
    build:
      context: ./service_users/ServiceUsers
    ports:
      - "5076:5076"   # <— Swagger и API Users будут на этом порту
    environment:
      SERVICE_NAME: "Service Users"
    networks:
      - task-network
      
  service_orders:
    build:
      context: ./service_orders/ServiceOrders
    ports:
      - "5074:5074"   # <— Swagger и API Orders будут на этом порту
    environment:
      SERVICE_NAME: "Service Orders"
    networks:
      - task-network

networks:
  task-network:
    driver: bridge
